version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports: 
      - 2368:2368
    depends_on:
      - "db"
    restart: always
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
    networks:
      - my-network
    
  db: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network:
