version: '3.6'

services:
  inventory:
    build:
      context: .
    volumes:
      - .:/projeto
    environment:
      - TEMPLATES_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
      - APPLY_TO_ALL=True
