version: '3'
services:
  todofront:
    build: todo-app/front-end
    depends_on:
      - todoback
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: todoback
  todoback:
    build: todo-app/back-end
    ports:
      - 3001:3001
  todotest:
    build: todo-app/tests
    depends_on:
      - todoback
      - todofront
    environment:
      FRONT_HOST: todofront
      FRONT_PORT: 3000